version: "3"
services:
  database:
    restart: always
    ports:
     - 5432:5432
    image: postgres
    volumes:
     - ./data/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
  service:
    build: ./
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./logs:/usr/artis/logs
