version: "3"
services:
  database:
    restart: always
    ports:
     - 5432:5432
    image: postgres
    env_file:
      - .env
  metabase:
    restart: always
    ports:
     - 3000:3000
    image: metabase
  service:
    build: ./
    env_file:
      - .env
    depends_on:
      - database
